stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: gcc:latest
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

test: 
  stage: test
  dependencies:
    - build
  script:
    - ./build/bin/test_sample

