variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: rikorose/gcc-cmake:latest
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/bin

test: 
  stage: test
  dependencies:
    - build
  script:
    - ./build/bin/parsedarg_test
