variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: dff9th/gcc-cmake:9.3.0-3.17.0
  script:
    - pwd
    - ls
    - ls include
    - ls include/gtest
    - mkdir build
    - cd build
    - CXX=g++ cmake ..
    - make
  artifacts:
    paths:
      - build/bin

test: 
  stage: test
  tags:
    - docker
  image: dff9th/gcc-cmake:9.3.0-3.17.0
  dependencies:
    - build
  script:
    - ./build/bin/all_test
