variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: dff9th/gcc-cmake:9.3.0-3.17.0
  script:
    - cp -r test/googletest/googlemock/include/gmock include/
    - cp -r test/googletest/googlemock/include/gmock include/
    - mkdir build
    - cd build
    - CXX=g++ cmake ..
    - make
  artifacts:
    paths:
      - build/bin

test: 
  stage: test
  tags:
    - docker
  image: dff9th/gcc-cmake:9.3.0-3.17.0
  dependencies:
    - build
  script:
    - cp -r test/googletest/googlemock/include/gmock include/
    - cp -r test/googletest/googlemock/include/gmock include/
    - ./build/bin/all_test
