variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: dff9th/gcc_cmake:9.3.0
  script:
    - mkdir build
    - cd build
    - CXX=/usr/local/bin/g++ cmake ..
    - make
  artifacts:
    paths:
      - build/bin

test: 
  stage: test
  dependencies:
    - build
  script:
    - ./build/bin/parsedarg_test
